name: Bug Report
description: Report a bug or issue with the Exam Countdown Extension
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.
  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 10, macOS 12.1, Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail. What happened? What did you expect to happen?
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, logs, etc.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: I have searched for similar issues and couldn't find any.
          required: true
        - label: I have tried the latest version of the extension.
          required: true
        - label: I have provided all the required information above.
          required: true
