name: Feature Request
description: Suggest a new feature or enhancement for the Exam Countdown Extension
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make the Exam Countdown Extension better for everyone.
  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. How should the feature work?
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Screenshots, mockups, or links to similar features in other extensions.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: I have searched for similar feature requests and couldn't find any.
          required: true
        - label: This feature would benefit other users as well.
          required: true
